### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by DanieleNardi** [PeterSommerlad/CUTE#24]
Hello,
I installed the Eclipse plugin, created a new Cute Project Suite inside my workspace (with one existing project, the one I want to write unit tests for), but I get more than 2K build errors, all of them like the following one:
`/home/daniele/eclipse-workspace/Biscottest/cute/cute_equals.h:89:3: error: template with C linkage
   template <typename ExpectedValue, typename ActualValue, bool select_non_integral_type>
   ^~~~~~~~`
I'm using GNU Make build with ARM GCC/G++ compiler (gcc-arm-none-eabi-6-2017-q4-major).

I guess it's something about project configuration, but I can't find what.

Regards,
Daniele

**Comment by PeterSommerlad** [comment]
First, I would try if you could compile a hello world project from your eclipse workspace.

Using the plug-in create a new CUTE project in your workspace. Does this compile?

Is your compiler actually compiling your code as C++? 

Without further information, it is hard to debug remotely.

the error message looks like you include a CUTE header with an extern "C" { open.

I recommend that you use www.cevelop.com that comes with the cute plugin pre-installed, if possible.

**Comment by DanieleNardi** [comment]
Hello,
yes, I can compile a c++ hello world project in my workspace.
A new CUTE project doesn't compile.
I expect so.
I didn't inckude anything, just created thw project with the plugin and launched the build.
I'll evaluate Cevelop.

________________________________
Da: Peter Sommerlad <notifications@github.com>
Inviato: giovedì 4 febbraio 2021 17:14
A: PeterSommerlad/CUTE <CUTE@noreply.github.com>
Cc: Daniele Nardi - Tecniplast S.p.A. <daniele.nardi@tecniplast.it>; Author <author@noreply.github.com>
Oggetto: Re: [PeterSommerlad/CUTE] Build errors (#24)


First, I would try if you could compile a hello world project from your eclipse workspace.

Using the plug-in create a new CUTE project in your workspace. Does this compile?

Is your compiler actually compiling your code as C++?

Without further information, it is hard to debug remotely.

the error message looks like you include a CUTE header with an extern "C" { open.

I recommend that you use www.cevelop.com<http://www.cevelop.com> that comes with the cute plugin pre-installed, if possible.

**Comment by PeterSommerlad** [comment]
Without more information, I can unfortunately be not of much help.

Seeing the compiler call generated might give me some hint what setting is wrong. 

It might be a tiny thing in the settings causing the code to be compiled wrongly. 
If you cross-compile settings can get tricky.
